language: java
jdk:
- oraclejdk8
sudo: required
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: AKIAJ6YWVFOX3GHDXVRQ
  secret_access_key:
    secure: h3fBfh/Vg7wD7A3mRIwXU6ZJFUmgM7PgGKAwTq7BR12oK+v3CUpjbhtAHk9EFTMy4Js/CWn3f38vSGuW06OI5pJQnRmBeO6dsfU1jh6ml+XhKO5MCQHjs/S7N6XYvSlMcSPByBmSCdfmOxyRPiAHPJEE1JHFWbPyGbVJ91X3yXw=
  region: us-east-1
  app: bridge-exporter-$TRAVIS_BRANCH-application
  env: bridge-exporter-$TRAVIS_BRANCH
  bucket_name: elasticbeanstalk-us-east-1-649232250620
  zip-file: target/Bridge-Exporter-2.0.war
  on:
    all_branches: true
